#### SHIFT + SPACE para pedir docs

In [2]:
!pip install jupyter numpy pandas matplotlib seaborn

Collecting jupyter
  Using cached jupyter-1.1.1-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting numpy
  Downloading numpy-2.2.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting pandas
  Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting matplotlib
  Downloading matplotlib-3.10.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting notebook (from jupyter)
  Downloading notebook-7.3.2-py3-none-any.whl.metadata (10 kB)
Collecting jupyter-console (from jupyter)
  Using cached jupyter_console-6.6.3-py3-none-any.whl.metadata (5.8 kB)
Collecting nbconvert (from jupyter)
  Downloading nbconvert-7.16.5-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: ipykernel in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from jupyter) (6.29.5)
Collecting ipywidgets (from jupyter)
  Using cached ipywidgets-8.1.5-py3-none-any.whl.metadata (2.3 kB)
Collecting jupyterlab (from jupyter)
  Downloading jupyterlab-4.3.4-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.1-cp313-cp313-win_amd64.whl.metadata (5.4 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.55.3-cp313-cp313-win_amd64.whl.metadata (168 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.4.8-cp313-cp313-win_amd64.whl.metadata (6.3 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from matplotlib) (24.2)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-11.1.0-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=2.3.1 (from matplotlib)
  Downloading pyparsing-3.2.1-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: six>=1.5 in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: comm>=0.1.1 in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from ipykernel->jupyter) (0.2.2)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from ipykernel->jupyter) (1.8.11)
Requirement already satisfied: ipython>=7.23.1 in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from ipykernel->jupyter) (8.31.0)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from ipykernel->jupyter) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from ipykernel->jupyter) (5.7.2)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from ipykernel->jupyter) (0.1.7)
Requirement already satisfied: nest-asyncio in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: psutil in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from ipykernel->jupyter) (6.1.1)
Requirement already satisfied: pyzmq>=24 in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from ipykernel->jupyter) (26.2.0)
Requirement already satisfied: tornado>=6.1 in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from ipykernel->jupyter) (6.4.2)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from ipykernel->jupyter) (5.14.3)
Collecting widgetsnbextension~=4.0.12 (from ipywidgets->jupyter)
  Using cached widgetsnbextension-4.0.13-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab-widgets~=3.0.12 (from ipywidgets->jupyter)
  Using cached jupyterlab_widgets-3.0.13-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: prompt-toolkit>=3.0.30 in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from jupyter-console->jupyter) (3.0.48)
Requirement already satisfied: pygments in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from jupyter-console->jupyter) (2.19.1)
Collecting async-lru>=1.0.0 (from jupyterlab->jupyter)
  Using cached async_lru-2.0.4-py3-none-any.whl.metadata (4.5 kB)
Collecting httpx>=0.25.0 (from jupyterlab->jupyter)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting jinja2>=3.0.3 (from jupyterlab->jupyter)
  Downloading jinja2-3.1.5-py3-none-any.whl.metadata (2.6 kB)
Collecting jupyter-lsp>=2.0.0 (from jupyterlab->jupyter)
  Using cached jupyter_lsp-2.2.5-py3-none-any.whl.metadata (1.8 kB)
Collecting jupyter-server<3,>=2.4.0 (from jupyterlab->jupyter)
  Downloading jupyter_server-2.15.0-py3-none-any.whl.metadata (8.4 kB)
Collecting jupyterlab-server<3,>=2.27.1 (from jupyterlab->jupyter)
  Using cached jupyterlab_server-2.27.3-py3-none-any.whl.metadata (5.9 kB)
Collecting notebook-shim>=0.2 (from jupyterlab->jupyter)
  Using cached notebook_shim-0.2.4-py3-none-any.whl.metadata (4.0 kB)
Collecting setuptools>=40.8.0 (from jupyterlab->jupyter)
  Downloading setuptools-75.8.0-py3-none-any.whl.metadata (6.7 kB)
Collecting beautifulsoup4 (from nbconvert->jupyter)
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting bleach!=5.0.0 (from bleach[css]!=5.0.0->nbconvert->jupyter)
  Using cached bleach-6.2.0-py3-none-any.whl.metadata (30 kB)
Collecting defusedxml (from nbconvert->jupyter)
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting jupyterlab-pygments (from nbconvert->jupyter)
  Using cached jupyterlab_pygments-0.3.0-py3-none-any.whl.metadata (4.4 kB)
Collecting markupsafe>=2.0 (from nbconvert->jupyter)
  Downloading MarkupSafe-3.0.2-cp313-cp313-win_amd64.whl.metadata (4.1 kB)
Collecting mistune<4,>=2.0.3 (from nbconvert->jupyter)
  Downloading mistune-3.1.0-py3-none-any.whl.metadata (1.7 kB)
Collecting nbclient>=0.5.0 (from nbconvert->jupyter)
  Downloading nbclient-0.10.2-py3-none-any.whl.metadata (8.3 kB)
Collecting nbformat>=5.7 (from nbconvert->jupyter)
  Using cached nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Collecting pandocfilters>=1.4.1 (from nbconvert->jupyter)
  Using cached pandocfilters-1.5.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting webencodings (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter)
  Using cached webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting tinycss2<1.5,>=1.1.0 (from bleach[css]!=5.0.0->nbconvert->jupyter)
  Using cached tinycss2-1.4.0-py3-none-any.whl.metadata (3.0 kB)
Collecting anyio (from httpx>=0.25.0->jupyterlab->jupyter)
  Downloading anyio-4.8.0-py3-none-any.whl.metadata (4.6 kB)
Collecting certifi (from httpx>=0.25.0->jupyterlab->jupyter)
  Downloading certifi-2024.12.14-py3-none-any.whl.metadata (2.3 kB)
Collecting httpcore==1.* (from httpx>=0.25.0->jupyterlab->jupyter)
  Using cached httpcore-1.0.7-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx>=0.25.0->jupyterlab->jupyter)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx>=0.25.0->jupyterlab->jupyter)
  Using cached h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: colorama in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.4.6)
Requirement already satisfied: decorator in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.19.2)
Requirement already satisfied: stack_data in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.6.3)
Requirement already satisfied: platformdirs>=2.5 in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (4.3.6)
Requirement already satisfied: pywin32>=300 in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (308)
Collecting argon2-cffi>=21.1 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached argon2_cffi-23.1.0-py3-none-any.whl.metadata (5.2 kB)
Collecting jupyter-events>=0.11.0 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading jupyter_events-0.11.0-py3-none-any.whl.metadata (5.8 kB)
Collecting jupyter-server-terminals>=0.4.4 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached jupyter_server_terminals-0.5.3-py3-none-any.whl.metadata (5.6 kB)
Collecting overrides>=5.0 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Collecting prometheus-client>=0.9 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading prometheus_client-0.21.1-py3-none-any.whl.metadata (1.8 kB)
Collecting pywinpty>=2.0.1 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading pywinpty-2.0.14-cp313-none-win_amd64.whl.metadata (5.2 kB)
Collecting send2trash>=1.8.2 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached Send2Trash-1.8.3-py3-none-any.whl.metadata (4.0 kB)
Collecting terminado>=0.8.3 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached terminado-0.18.1-py3-none-any.whl.metadata (5.8 kB)
Collecting websocket-client>=1.7 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached websocket_client-1.8.0-py3-none-any.whl.metadata (8.0 kB)
Collecting babel>=2.10 (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter)
  Using cached babel-2.16.0-py3-none-any.whl.metadata (1.5 kB)
Collecting json5>=0.9.0 (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter)
  Downloading json5-0.10.0-py3-none-any.whl.metadata (34 kB)
Collecting jsonschema>=4.18.0 (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter)
  Using cached jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
Collecting requests>=2.31 (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting fastjsonschema>=2.15 (from nbformat>=5.7->nbconvert->jupyter)
  Using cached fastjsonschema-2.21.1-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: wcwidth in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from prompt-toolkit>=3.0.30->jupyter-console->jupyter) (0.2.13)
Collecting soupsieve>1.2 (from beautifulsoup4->nbconvert->jupyter)
  Using cached soupsieve-2.6-py3-none-any.whl.metadata (4.6 kB)
Collecting sniffio>=1.1 (from anyio->httpx>=0.25.0->jupyterlab->jupyter)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting argon2-cffi-bindings (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached argon2_cffi_bindings-21.2.0-cp36-abi3-win_amd64.whl.metadata (6.7 kB)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->jupyter) (0.8.4)
Collecting attrs>=22.2.0 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter)
  Downloading attrs-24.3.0-py3-none-any.whl.metadata (11 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter)
  Using cached jsonschema_specifications-2024.10.1-py3-none-any.whl.metadata (3.0 kB)
Collecting referencing>=0.28.4 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter)
  Using cached referencing-0.35.1-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.7.1 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter)
  Downloading rpds_py-0.22.3-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Collecting python-json-logger>=2.0.4 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading python_json_logger-3.2.1-py3-none-any.whl.metadata (4.1 kB)
Collecting pyyaml>=5.3 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading PyYAML-6.0.2-cp313-cp313-win_amd64.whl.metadata (2.1 kB)
Collecting rfc3339-validator (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached rfc3339_validator-0.1.4-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting rfc3986-validator>=0.1.1 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached rfc3986_validator-0.1.1-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter)
  Downloading charset_normalizer-3.4.1-cp313-cp313-win_amd64.whl.metadata (36 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter)
  Downloading urllib3-2.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: executing>=1.2.0 in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel->jupyter) (2.1.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel->jupyter) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\ivanx\documents\github\python\.venv\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel->jupyter) (0.2.3)
Collecting fqdn (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting isoduration (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Collecting jsonpointer>1.13 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached jsonpointer-3.0.0-py2.py3-none-any.whl.metadata (2.3 kB)
Collecting uri-template (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
Collecting webcolors>=24.6.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached webcolors-24.11.1-py3-none-any.whl.metadata (2.2 kB)
Collecting cffi>=1.0.1 (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading cffi-1.17.1-cp313-cp313-win_amd64.whl.metadata (1.6 kB)
Collecting pycparser (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Collecting arrow>=0.15.0 (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached arrow-1.3.0-py3-none-any.whl.metadata (7.5 kB)
Collecting types-python-dateutil>=2.8.10 (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading types_python_dateutil-2.9.0.20241206-py3-none-any.whl.metadata (2.1 kB)
Using cached jupyter-1.1.1-py2.py3-none-any.whl (2.7 kB)
Downloading numpy-2.2.1-cp313-cp313-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.6/12.6 MB 9.1 MB/s eta 0:00:02
   ---------- ----------------------------- 3.4/12.6 MB 8.4 MB/s eta 0:00:02
   ------------------ --------------------- 5.8/12.6 MB 9.5 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.6 MB 10.1 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.6 MB 10.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 10.3 MB/s eta 0:00:00
Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   -------- ------------------------------- 2.4/11.5 MB 11.3 MB/s eta 0:00:01
   --------------- ------------------------ 4.5/11.5 MB 11.4 MB/s eta 0:00:01
   ------------------------- -------------- 7.3/11.5 MB 11.3 MB/s eta 0:00:01
   --------------------------------- ------ 9.7/11.5 MB 11.2 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 10.8 MB/s eta 0:00:00
Downloading matplotlib-3.10.0-cp313-cp313-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ----------- ---------------------------- 2.4/8.0 MB 11.3 MB/s eta 0:00:01
   --------------------------- ------------ 5.5/8.0 MB 10.8 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.0 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 10.4 MB/s eta 0:00:00
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading contourpy-1.3.1-cp313-cp313-win_amd64.whl (220 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.55.3-cp313-cp313-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 2.2/2.2 MB 10.6 MB/s eta 0:00:00
Downloading kiwisolver-1.4.8-cp313-cp313-win_amd64.whl (71 kB)
Downloading pillow-11.1.0-cp313-cp313-win_amd64.whl (2.6 MB)
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   ----------------------------------- ---- 2.4/2.6 MB 11.6 MB/s eta 0:00:01
   ---------------------------------------- 2.6/2.6 MB 10.9 MB/s eta 0:00:00
Downloading pyparsing-3.2.1-py3-none-any.whl (107 kB)
Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
Using cached ipywidgets-8.1.5-py3-none-any.whl (139 kB)
Using cached jupyter_console-6.6.3-py3-none-any.whl (24 kB)
Downloading jupyterlab-4.3.4-py3-none-any.whl (11.7 MB)
   ---------------------------------------- 0.0/11.7 MB ? eta -:--:--
   -------- ------------------------------- 2.4/11.7 MB 11.4 MB/s eta 0:00:01
   ------------- -------------------------- 3.9/11.7 MB 9.6 MB/s eta 0:00:01
   ------------------------ --------------- 7.1/11.7 MB 11.3 MB/s eta 0:00:01
   -------------------------------- ------- 9.4/11.7 MB 11.4 MB/s eta 0:00:01
   ---------------------------------------  11.5/11.7 MB 11.1 MB/s eta 0:00:01
   ---------------------------------------- 11.7/11.7 MB 10.8 MB/s eta 0:00:00
Downloading nbconvert-7.16.5-py3-none-any.whl (258 kB)
Downloading notebook-7.3.2-py3-none-any.whl (13.2 MB)
   ---------------------------------------- 0.0/13.2 MB ? eta -:--:--
   ------- -------------------------------- 2.4/13.2 MB 11.4 MB/s eta 0:00:01
   -------------- ------------------------- 4.7/13.2 MB 11.4 MB/s eta 0:00:01
   --------------------- ------------------ 7.1/13.2 MB 11.4 MB/s eta 0:00:01
   --------------------------- ------------ 8.9/13.2 MB 11.4 MB/s eta 0:00:01
   ------------------------------------ --- 12.1/13.2 MB 11.4 MB/s eta 0:00:01
   ---------------------------------------- 13.2/13.2 MB 11.1 MB/s eta 0:00:00
Using cached async_lru-2.0.4-py3-none-any.whl (6.1 kB)
Using cached bleach-6.2.0-py3-none-any.whl (163 kB)
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.7-py3-none-any.whl (78 kB)
Downloading jinja2-3.1.5-py3-none-any.whl (134 kB)

#### Import Dataset and Libraries

In [5]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from matplotlib import pyplot as py

from urllib.request import urlretrieve
italy_covid_url = 'https://gist.githubusercontent.com/aakashns/f6a004fa20c84fec53262f9a8bfee775/raw/f309558b1cf5103424cef58e2ecb8704dcd4d74c/italy-covid-daywise.csv'

urlretrieve(italy_covid_url, 'italy-covid-daywise.csv') #trying to retrive the csv file attachted to the url

('italy-covid-daywise.csv', <http.client.HTTPMessage at 0x24ceef76b10>)

In [7]:
covid_df=pd.read_csv('italy-covid-daywise.csv') #pandas reading csv file
covid_df.head() #displaying the first 5 rows of the csv file

         date  new_cases  new_deaths  new_tests
0  2019-12-31        0.0         0.0        NaN
1  2020-01-01        0.0         0.0        NaN
2  2020-01-02        0.0         0.0        NaN
3  2020-01-03        0.0         0.0        NaN
4  2020-01-04        0.0         0.0        NaN

In [8]:
covid_df.info() #displaying the information of the csv file

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        248 non-null    object
 1   new_cases   248 non-null    float64
 2   new_deaths  248 non-null    float64
 3   new_tests   135 non-null    float64
dtypes: float64(3), object(1)
memory usage: 7.9+ KB

In [9]:
covid_df.describe() #displaying the statistics of the csv file

         new_cases  new_deaths     new_tests
count   248.000000  248.000000    135.000000
mean   1094.818548  143.133065  31699.674074
std    1554.508002  227.105538  11622.209757
min    -148.000000  -31.000000   7841.000000
25%     123.000000    3.000000  25259.000000
50%     342.000000   17.000000  29545.000000
75%    1371.750000  175.250000  37711.000000
max    6557.000000  971.000000  95273.000000

In [10]:
covid_df.columns #displaying the columns of the csv file

Index(['date', 'new_cases', 'new_deaths', 'new_tests'], dtype='object')

In [11]:
covid_df.shape #displaying the shape of the csv file

(248, 4)

In [12]:
covid_df['date'] = pd.to_datetime(covid_df.date) #converting the date column to datetime

In [13]:
covid_df.head()

        date  new_cases  new_deaths  new_tests
0 2019-12-31        0.0         0.0        NaN
1 2020-01-01        0.0         0.0        NaN
2 2020-01-02        0.0         0.0        NaN
3 2020-01-03        0.0         0.0        NaN
4 2020-01-04        0.0         0.0        NaN

In [14]:
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        248 non-null    datetime64[ns]
 1   new_cases   248 non-null    float64
 2   new_deaths  248 non-null    float64
 3   new_tests   135 non-null    float64
dtypes: datetime64[ns](1), float64(3)
memory usage: 7.9 KB

In [17]:
covid_df_copy = covid_df.copy() #copying the dataframe to another dataframe, dont want to change the original dataframe

covid_df_copy['new_deaths'] = covid_df_copy['new_deaths'].fillna(0) #filling the null values with 0
covid_df_copy['new_cases'] = covid_df_copy['new_cases'].fillna(0) #filling the null values with 0
covid_df_copy['new_tests'] = covid_df_copy['new_tests'].fillna(0) #filling the null values with 0
covid_df_copy['new_deaths'] = covid_df_copy['new_deaths'].astype(int) #converting the new_deaths column to integer
covid_df_copy['new_cases'] = covid_df_copy['new_cases'].astype(int) #converting the new_cases column to integer
covid_df_copy['new_tests'] = covid_df_copy['new_tests'].astype(int) #converting the new_tests column to integer
covid_df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        248 non-null    datetime64[ns]
 1   new_cases   248 non-null    int64
 2   new_deaths  248 non-null    int64
 3   new_tests   248 non-null    int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 7.9 KB

In [18]:
covid_df_copy.new_tests[2] = 1000 #changing the value of new_tests column at index 2 to 1000
covid_df_copy.head()

C:\Users\ivanx\AppData\Local\Temp\ipykernel_25644\3283558305.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  covid_df_copy.new_tests[2] = 1000 #changing the value of new_tests column at index 2 to 1000
C:\Users\ivanx\AppData\Local\Temp\ipykernel_25644\3283558305.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  covid_df_copy.new_tests[2] = 1000 #changing the value of new_tests column at index 2 to 1000

        date  new_cases  new_deaths  new_tests
0 2019-12-31          0           0          0
1 2020-01-01          0           0          0
2 2020-01-02          0           0       1000
3 2020-01-03          0           0          0
4 2020-01-04          0           0          0

In [19]:
covid_df.head()

        date  new_cases  new_deaths  new_tests
0 2019-12-31        0.0         0.0        NaN
1 2020-01-01        0.0         0.0        NaN
2 2020-01-02        0.0         0.0        NaN
3 2020-01-03        0.0         0.0        NaN
4 2020-01-04        0.0         0.0        NaN

In [22]:
covid_df.loc[243] #displaying the row at index 243

date          2020-08-30 00:00:00
new_cases                  1444.0
new_deaths                    1.0
new_tests                 53541.0
Name: 243, dtype: object

In [24]:
covid_df_copy.at[0, 'new_tests']
covid_df_copy.head()

        date  new_cases  new_deaths  new_tests
0 2019-12-31          0           0          0
1 2020-01-01          0           0          0
2 2020-01-02          0           0       1000
3 2020-01-03          0           0          0
4 2020-01-04          0           0          0

### Get first not NaN value from column

In [25]:
covid_df.new_tests.first_valid_index() #displaying the first valid index of new_tests column

111

In [28]:
covid_df_copy.loc[200:210]

          date  new_cases  new_deaths  new_tests
200 2020-07-18        231          11      27569
201 2020-07-19        249          14      20621
202 2020-07-20        218           3      14121
203 2020-07-21        190          13      23915
204 2020-07-22        128          15      29288
205 2020-07-23        280           9      33018
206 2020-07-24        306          10      28970
207 2020-07-25        252           5      28059
208 2020-07-26        274           5      25177
209 2020-07-27        254           5      19374
210 2020-07-28        168           5      25341

#### Get random sample

In [29]:
covid_df.sample(10) #displaying 10 random rows

          date  new_cases  new_deaths  new_tests
38  2020-02-07        0.0         0.0        NaN
24  2020-01-24        0.0         0.0        NaN
25  2020-01-25        0.0         0.0        NaN
207 2020-07-25      252.0         5.0    28059.0
73  2020-03-13     2651.0       189.0        NaN
74  2020-03-14     2547.0       252.0        NaN
126 2020-05-05     1221.0       195.0    32211.0
48  2020-02-17        0.0         0.0        NaN
65  2020-03-05      587.0        27.0        NaN
153 2020-06-01      355.0        75.0    18053.0

In [37]:
total_deaths = covid_df.new_deaths.sum() #sum of new_deaths column
total_cases = covid_df.new_cases.sum() #sum of new_cases column
total_tests = covid_df.new_tests.sum() #sum of new_tests column

print("Total Deaths: {:.0f}\nTotal Cases: {:.0f}\nTotal Tests: {:.0f}".format(total_deaths, total_cases, total_tests))

Total Deaths: 35497
Total Cases: 271515
Total Tests: 4279456

In [39]:
total_death_rate = total_deaths/total_cases #death rate
print("Total Death Rate: {:.2f}%".format(total_death_rate*100))

Total Death Rate: 13.07%

### Querying and Sorting

In [43]:
high_new_cases = covid_df.new_cases > 1000 #filtering the rows with new_cases greater than 1000
high_new_cases

covid_df[high_new_cases] #displaying the rows with new_cases greater than 1000

          date  new_cases  new_deaths  new_tests
68  2020-03-08     1247.0        36.0        NaN
69  2020-03-09     1492.0       133.0        NaN
70  2020-03-10     1797.0        98.0        NaN
72  2020-03-12     2313.0       196.0        NaN
73  2020-03-13     2651.0       189.0        NaN
..         ...        ...         ...        ...
241 2020-08-28     1409.0         5.0    65135.0
242 2020-08-29     1460.0         9.0    64294.0
243 2020-08-30     1444.0         1.0    53541.0
244 2020-08-31     1365.0         4.0    42583.0
247 2020-09-03     1326.0         6.0        NaN

[72 rows x 4 columns]

In [44]:
covid_df.sort_values('new_cases', ascending=False).head() #sorting the dataframe by new_cases column in descending order

         date  new_cases  new_deaths  new_tests
82 2020-03-22     6557.0       795.0        NaN
87 2020-03-27     6153.0       660.0        NaN
81 2020-03-21     5986.0       625.0        NaN
89 2020-03-29     5974.0       887.0        NaN
88 2020-03-28     5959.0       971.0        NaN

#### Extract data from datetime

In [46]:
covid_df['year'] = pd.DatetimeIndex(covid_df.date).year #extracting the year from the date column
covid_df['month'] = pd.DatetimeIndex(covid_df.date).month #extracting the month from the date column
covid_df['day'] = pd.DatetimeIndex(covid_df.date).day #extracting the day from the date column
covid_df['weekday'] = pd.DatetimeIndex(covid_df.date).weekday #extracting the weekday from the date column

# Convert Int to Weekday
weekday_map = {0:'Monday', 1:'Tuesday', 2:'Wednesday', 3:'Thursday', 4:'Friday', 5:'Saturday', 6:'Sunday'}
covid_df['weekday'] = covid_df['weekday'].map(weekday_map)
covid_df.head()

        date  new_cases  new_deaths  new_tests  year  month  day    weekday
0 2019-12-31        0.0         0.0        NaN  2019     12   31    Tuesday
1 2020-01-01        0.0         0.0        NaN  2020      1    1  Wednesday
2 2020-01-02        0.0         0.0        NaN  2020      1    2   Thursday
3 2020-01-03        0.0         0.0        NaN  2020      1    3     Friday
4 2020-01-04        0.0         0.0        NaN  2020      1    4   Saturday

In [47]:
may_covid = covid_df[covid_df.month == 5] #filtering the rows with month 5
may_covid.head()

          date  new_cases  new_deaths  new_tests  year  month  day   weekday
122 2020-05-01     1872.0       285.0    43732.0  2020      5    1    Friday
123 2020-05-02     1965.0       269.0    31231.0  2020      5    2  Saturday
124 2020-05-03     1900.0       474.0    27047.0  2020      5    3    Sunday
125 2020-05-04     1389.0       174.0    22999.0  2020      5    4    Monday
126 2020-05-05     1221.0       195.0    32211.0  2020      5    5   Tuesday

In [49]:
may_covid_metrics = may_covid[['new_cases', 'new_deaths', 'new_tests']] #selecting the columns new_cases, new_deaths, new_tests
total_may_cases, total_may_deaths, total_may_tests = may_covid_metrics.sum() #sum of new_cases, new_deaths, new_tests
print("Total Cases in May: {:.0f}\nTotal Deaths in May: {:.0f}\nTotal Tests in May: {:.0f}".format(total_may_cases, total_may_deaths, total_may_tests))

Total Cases in May: 29073
Total Deaths in May: 5658
Total Tests in May: 1078720

In [50]:
# Average new cases for Sunday
may_sunday_mean_cases = may_covid[may_covid.weekday == 'Sunday'].new_cases.mean()
print("Average new cases for Sundays in May: {:.2f}".format(may_sunday_mean_cases))

Average new cases for Sundays in May: 988.60

#### Grouping aggregation